name: Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

# Evita execuções duplicadas simultâneas
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Scan único com configuração flexível
  semgrep-security:
    #uses: ./.github/workflows/semgrep-scan.yml # repositório local
    uses: parad0x-0xff/.github/.github/workflows/semgrep-scan.yml@main # repositório remoto
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
