name: Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

# Evita execuções duplicadas simultâneas
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Scan único com configuração flexível
  semgrep-security:
    #uses: parad0x-0xff/.github/.github/workflows/semgrep-scan.yml@main # repositório remoto
    uses: ./.github/workflows/semgrep-scan.yml # repositório local


  # Opção 3: Scan crítico apenas em PRs
  #semgrep-critical:
  #  uses: ./.github/workflows/semgrep-scan.yml
  #  with:
  #    semgrep-rules: '.semgrep.yml'  
  #    fail-on-findings: true  # Falhar se encontrar vulnerabilidades críticas
  #    exclude-patterns: 'node_modules/**,dist/**,build/**,*.min.js,*.bundle.js'
  #    severity-filter: 'ERROR'  # Apenas erros críticos
  #  secrets: inherit
  #  if: github.event_name == 'pull_request'  
  
