name: Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Evita execuções duplicadas simultâneas
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semgrep-security-scan:
    uses: ./.github/workflows/semgrep-scan.yml # repositório local
    with:
      scan-mode: ${{ github.event_name == 'pull_request' && 'diff' || 'full' }}
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}