name: Semgrep Security Scan

# 'workflow_call' permite que este workflow seja chamado por outros.
on:
  workflow_call:
    inputs:
      semgrep-rules:
        description: 'Análise estática de código com Semgrep'
        required: false
        type: string
        default: 'p/ci'
      fail-on-findings:
        description: 'Falhar se encontrar vulnerabilidades críticas/altas'
        required: false
        type: boolean
        default: false
    secrets:
      SEMGREP_APP_TOKEN:
        description: 'Token do Semgrep App'
        required: false

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  semgrep:
    name: semgrep-oss/scan
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Timeout para evitar travamentos
    
    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')
    
    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep
    
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    
    steps:
      # Fetch project source with GitHub Actions Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Para análise completa do histórico

      # Run the "semgrep scan" command on the command line of the docker image
      - name: Run Semgrep scan
        id: semgrep
        run: |
          semgrep scan \
            --sarif-output semgrep.sarif \
            --exclude 'node_modules/**,dist/**,build/**,*.min.js,*.bundle.js' \
            --severity ERROR \
            --timeout 1800 \
            --max-memory 4096


      - name: Upload SARIF results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: semgrep-${{ github.event_name }}-${{ github.sha }}
        if: always()

      - name: Upload SARIF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep.sarif
          retention-days: 30
        if: always()