name: Weekly Security Metrics Report

on:
  # A cada 5 minutos no minuto 5
  #schedule:
  #  - cron: '*/5 * * * *'
  # Permite a execução manual para relatórios sob demanda
  workflow_dispatch:

jobs:
  generate-report:
    name: Generate Vulnerability Report
    runs-on: ubuntu-latest
    permissions:
      security-events: read
    
    steps:
      - name: Generate Report
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          REPO: ${{ github.repository }}
        run: |
          # Calcula a data de 7 dias atrás no formato ISO 8601
          since_date=$(date -u -d "7 days ago" +'%Y-%m-%dT%H:%M:%SZ')

          echo "📊 Relatório de Segurança Semanal para o repositório: $REPO"
          echo "Período: $since_date até $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          echo "---------------------------------------------------------"

          # Usa o GitHub CLI (gh) para buscar os alertas. É mais fácil que usar curl.
          # O 'gh' já vem instalado nos runners do GitHub.
          
          # Busca alertas que foram FECHADOS no período
          # O estado 'fixed' é um subconjunto de 'dismissed' que foi corrigido por código
          fixed_alerts=$(gh api "repos/$REPO/code-scanning/alerts?state=fixed&per_page=100" --jq ".[] | select(.fixed_at > \"$since_date\")")
          
          # Conta quantos alertas foram encontrados
          fixed_count=$(echo "$fixed_alerts" | jq -s 'length')

          echo "✅ Vulnerabilidades Corrigidas na Última Semana: $fixed_count"
          
          # Se houver alertas corrigidos, lista os 5 mais recentes
          if [ "$fixed_count" -gt 0 ]; then
            echo ""
            echo "Detalhes das últimas correções:"
            echo "$fixed_alerts" | jq -r '. | "  - (#\(.number)) \(.rule.name) corrigido em \(.fixed_at)"' | head -n 5
          fi

          echo "---------------------------------------------------------"

          # Busca alertas que ainda estão ABERTOS
          open_alerts_count=$(gh api "repos/$REPO/code-scanning/alerts?state=open" --jq 'length')
          echo "🔥 Total de Vulnerabilidades Abertas Atualmente: $open_alerts_count"